serviceAccount:
  name: aws-load-balancer-controller
  annotations:
    "eks.amazonaws.com/role-arn": "arn:aws:iam::427509263767:role/4054-shubhams-lbc-iam-role"

vpcId: vpc-031aa180ef97dd109
region: us-east-1
clusterName: 4054-shubhams-eks