apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeseal-secret
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ProboticsX/Kubernetes-Projects.git'
    path: 02-Udemy-ArgoCD/06-kubeseal-secrets/argo-cd
    targetRevision: main
    helm:
      releaseName: kubeseal-secret
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true