apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-custom-artifact
  labels:
    app:  nginx-custom-artifact
spec:
  replicas: 3  # Number of pod replicas
  selector:
    matchLabels:
      app:  nginx-custom-artifact
  template:
    metadata:
      labels:
        app:  nginx-custom-artifact
    spec:
      containers:
      - name:  nginx-custom-artifact
        image: nginx:1.23.0  # You can specify the version of Nginx
        ports:
        - containerPort: 80  # Exposing port 80