---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appsecret
  namespace: default
spec:
  encryptedData:
    apikey: AgBBt3IoHWGzQXryXvMcY0Rjys8LyE4S+7Jwsu6LGYn4qtgJ9sUrrz6Upz5hcJTSMnAtOo/XUFgCBVJMnKpFjQP2aDkE3Zz56oRxuXpgR5dkhxhLVmmt6iTjaIJ393o0ybGHFQDp9ReQD42UkRUSm7wTBBk976/p7++EYYn6jLzN91JkYVshWmDyd3nf4LjLjbU0YEO3fZN+ovlTNpoOzwX2z0mU4/PZFd4lvkP6sQo8gqiV0k6h+XB/VfRocooebkCXvCisucGLqOk9oF+wqKtRf+aSajX22n8UecnN8RH+EykYzbddi+gFox80CDTZZN8JIewTyrriJ2T70+5gg2GkbVPaMG39z54s859nZy1Z0kkkyFvxedfk8aSR294ADpFJ7wQsN71D3EnWtUMSMDXwUb0hhi7nzLEr8/IzT36/SWgDTzGLtQJYBPVz9jf5LBsMEjj62uc9x9Cx26hPheazB4QCju0sF5b+Ex7LS4Skr8NNUM8F74nOCr0IM3ZeWAP0oinJfEM6+XEtSjkTIK4HUC59idJ12FSzD9WpoYw9qWM/PJg4FcOU4dnt5TQT8FS+QoyOAh1YgC7k3eHbg3nrc1gTU80I/Fmm6v43bDsy7dhotxp6nMfbAyC/eG41uJF2ukFdDaj0fLhkNIMqbBi0qVNcjZy2cOt0RBfVh8EaJ7xhwhvcLzb4Nbh4IB3atlnWk/6GGEPX3gsD/aR/ze9/8o9HRu8Wfkgc+QS0cPrNmwmhRFlU+KA=
  template:
    metadata:
      creationTimestamp: null
      name: appsecret
      namespace: default
    type: Opaque
