apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasks-pvc
spec:
  volumeName: tasks-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests: 
      storage: 1Gi