apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: welcome
  template:
    metadata:
      labels:
        app: welcome
    spec:
      containers:
      - name: welcome
        image: shubham0403/project2-welcome:2.0
        ports:
        - containerPort: 3001