apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-sql
data:
  init-db.sql: |
    USE mydatabase
    CREATE TABLE IF NOT EXISTS users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      email TEXT,
      status VARCHAR(50) DEFAULT 'pending'
    );
    INSERT INTO users (name, email) VALUES ('John Doe', 'john@example.com');