---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1 # cannot be 2 because aws-ebs volumes are scheduled in single zone only, but the two private nodes are in 1a and 1b
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword" # Set your root password
            - name: MYSQL_DATABASE
              value: "mydatabase"   # Database name where the script will run
            - name: MYSQL_USER
              value: "myuser"
            - name: MYSQL_PASSWORD
              value: "mypassword"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: init-db-volume
              mountPath: /docker-entrypoint-initdb.d
            - name: mysql-storage
              mountPath: /var/lib/mysql  # Default path for MySQL data
      volumes:
        - name: init-db-volume
          configMap:
            name: init-db-sql  # Reference to the ConfigMap
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc  # Use the PVC created earlier